# Generated by Django 4.0.6 on 2022-07-24 08:56

from django.db import migrations, models
import django.db.models.deletion
import filesystem.crypto


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('token', models.CharField(default=filesystem.crypto.get_random_string, max_length=32, primary_key=True, serialize=False, unique=True)),
                ('write_key', models.CharField(default=filesystem.crypto.get_random_string, max_length=32)),
                ('data', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('user_name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('root_token', models.CharField(default=filesystem.crypto.get_random_string, max_length=32)),
                ('public_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Share',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.file')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
